# 1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type. 

In [1]:
import numpy as np

# Create the array
arr = np.arange(6)

# Print the array and its data type
print(arr)
print("Data type of the array:", arr.dtype)


[0 1 2 3 4 5]
Data type of the array: int64


# 2. Given a NumPy array 'arr', check if its data type is float64. 
## arr = np.array([1.5, 2.6, 3.7])

In [2]:
import numpy as np

# Given array
arr = np.array([1.5, 2.6, 3.7])

# Check if the data type is float64
is_float64 = arr.dtype == np.float64

print("Is the array's data type float64?", is_float64)


Is the array's data type float64? True


# 3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

In [3]:
import numpy as np

# Create the array with complex numbers
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)

# Print the array and its data type
print(arr)
print("Data type of the array:", arr.dtype)


[1.+2.j 3.+4.j 5.+6.j]
Data type of the array: complex128


# 4. Convert an existing NumPy array 'arr' of integers to float32 data type

In [4]:
import numpy as np

# Example array of integers
arr = np.array([1, 2, 3, 4, 5])

# Convert to float32
arr_float32 = arr.astype(np.float32)

# Print the original and converted arrays along with their data types
print("Original array:", arr)
print("Original data type:", arr.dtype)
print("Converted array:", arr_float32)
print("Converted data type:", arr_float32.dtype)


Original array: [1 2 3 4 5]
Original data type: int64
Converted array: [1. 2. 3. 4. 5.]
Converted data type: float32


# 5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

In [5]:
import numpy as np

# Example array with float64 data type
arr = np.array([1.123456789, 2.123456789, 3.123456789], dtype=np.float64)

# Convert to float32
arr_float32 = arr.astype(np.float32)

# Print the original and converted arrays along with their data types
print("Original array:", arr)
print("Original data type:", arr.dtype)
print("Converted array:", arr_float32)
print("Converted data type:", arr_float32.dtype)


Original array: [1.12345679 2.12345679 3.12345679]
Original data type: float64
Converted array: [1.1234568 2.1234567 3.1234567]
Converted data type: float32


# 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.

In [6]:
import numpy as np

def array_attributes(arr):
    shape = arr.shape
    size = arr.size
    dtype = arr.dtype
    return shape, size, dtype

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, size, dtype = array_attributes(arr)

print("Shape:", shape)
print("Size:", size)
print("Data type:", dtype)


Shape: (2, 3)
Size: 6
Data type: int64


# 7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

In [7]:
import numpy as np

def array_dimension(arr):
    return arr.ndim

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]])
dimension = array_dimension(arr)

print("Dimensionality:", dimension)


Dimensionality: 2


# 8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

In [8]:
import numpy as np

def item_size_info(arr):
    item_size = arr.itemsize
    total_size = arr.nbytes
    return item_size, total_size

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]])
item_size, total_size = item_size_info(arr)

print("Item size (in bytes):", item_size)
print("Total size (in bytes):", total_size)


Item size (in bytes): 8
Total size (in bytes): 48


# 9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array

In [9]:
import numpy as np

def array_strides(arr):
    return arr.strides

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]])
strides = array_strides(arr)

print("Strides:", strides)


Strides: (24, 8)


# 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

In [10]:
import numpy as np

def shape_stride_relationship(arr):
    shape = arr.shape
    strides = arr.strides
    return shape, strides

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, strides = shape_stride_relationship(arr)

print("Shape:", shape)
print("Strides:", strides)


Shape: (2, 3)
Strides: (24, 8)


# 11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements

In [1]:
import numpy as np

def create_zeros_array(n):
    return np.zeros(n)

# Example usage
n = 5
zeros_array = create_zeros_array(n)

print("Array of zeros:", zeros_array)


Array of zeros: [0. 0. 0. 0. 0.]


# 12. Write a function create_ones_matrix that takes integers rows and cols as inputs and generates a 2D NumPy array filled with ones of size rows x cols.

In [2]:
import numpy as np

def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

# Example usage
rows = 3
cols = 4
ones_matrix = create_ones_matrix(rows, cols)

print("Matrix of ones:\n", ones_matrix)


Matrix of ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# 13. Write a function generate_range_array that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from start, ending at stop (exclusive), and with the specified step.

In [3]:
import numpy as np

def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

# Example usage
start = 0
stop = 10
step = 2
range_array = generate_range_array(start, stop, step)

print("Range array:", range_array)


Range array: [0 2 4 6 8]


# 14. Design a function generate_linear_space that takes two floats start, stop, and an integer num as arguments and generates a NumPy array with num equally spaced values between start and stop (inclusive).

In [4]:
import numpy as np

def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

# Example usage
start = 0.0
stop = 1.0
num = 5
linear_space_array = generate_linear_space(start, stop, num)

print("Linear space array:", linear_space_array)


Linear space array: [0.   0.25 0.5  0.75 1.  ]


# 15. Create a function create_identity_matrix that takes an integer n as input and generates a square identity matrix of size n x n using numpy.eye.

In [5]:
import numpy as np

def create_identity_matrix(n):
    return np.eye(n)

# Example usage
n = 4
identity_matrix = create_identity_matrix(n)

print("Identity matrix:\n", identity_matrix)


Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# 16. Write a function that takes a Python list and converts it into a NumPy array.

In [7]:
import numpy as np

def list_to_numpy_array(py_list):
    return np.array(py_list)

# Example usage
py_list = [1, 2, 3, 4, 5]
numpy_array = list_to_numpy_array(py_list)

print("Python list:", py_list)
print("NumPy array:", numpy_array)


Python list: [1, 2, 3, 4, 5]
NumPy array: [1 2 3 4 5]


# 17. Create a NumPy array and demonstrate the use of numpy.view to create a new array object with the same data.

In [8]:
import numpy as np

# Create an original NumPy array
original_array = np.array([1, 2, 3, 4, 5])

# Create a new array object using the view method
view_array = original_array.view()

# Print both arrays and their memory addresses to show they share the same data
print("Original array:", original_array)
print("View array:", view_array)

# Check if both arrays share the same data
print("Original array base:", original_array.base)
print("View array base:", view_array.base)

# Modify the original array to see if changes are reflected in the view
original_array[0] = 99
print("\nAfter modifying the original array:")
print("Original array:", original_array)
print("View array:", view_array)


Original array: [1 2 3 4 5]
View array: [1 2 3 4 5]
Original array base: None
View array base: [1 2 3 4 5]

After modifying the original array:
Original array: [99  2  3  4  5]
View array: [99  2  3  4  5]


# 18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [9]:
import numpy as np

def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

# Example usage
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Concatenate along the first axis (rows)
concatenated_array_axis0 = concatenate_arrays(arr1, arr2, axis=0)
print("Concatenated along axis 0:\n", concatenated_array_axis0)

# Concatenate along the second axis (columns)
concatenated_array_axis1 = concatenate_arrays(arr1, arr2, axis=1)
print("Concatenated along axis 1:\n", concatenated_array_axis1)


Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


# 19.  Create two NumPy arrays with different shapes and concatenate them horizontally using numpy.concatenate.

In [10]:
import numpy as np

# Create two arrays with different shapes but the same number of rows
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6, 7], [8, 9, 10]])

# Concatenate the arrays horizontally
concatenated_array = np.concatenate((arr1, arr2), axis=1)

print("Array 1:\n", arr1)
print("Array 2:\n", arr2)
print("Concatenated horizontally:\n", concatenated_array)


Array 1:
 [[1 2]
 [3 4]]
Array 2:
 [[ 5  6  7]
 [ 8  9 10]]
Concatenated horizontally:
 [[ 1  2  5  6  7]
 [ 3  4  8  9 10]]


 # 20. Write a function that vertically stacks multiple NumPy arrays given as a list.

In [11]:
import numpy as np

def vertically_stack_arrays(arr_list):
    return np.vstack(arr_list)

# Example usage
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr3 = np.array([[9, 10], [11, 12]])

# List of arrays to stack
arrays_to_stack = [arr1, arr2, arr3]

# Vertically stack the arrays
stacked_array = vertically_stack_arrays(arrays_to_stack)

print("Stacked array:\n", stacked_array)


Stacked array:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


# 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.

In [12]:
import numpy as np

def create_range_array(start, stop, step):
    # Adjust stop to be inclusive
    stop_adjusted = stop + step if step > 0 else stop - step
    return np.arange(start, stop_adjusted, step)

# Example usage
start = 0
stop = 10
step = 2
range_array = create_range_array(start, stop, step)

print("Range array:", range_array)


Range array: [ 0  2  4  6  8 10]


# 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive)

In [13]:
import numpy as np

def generate_equal_spaced_array():
    return np.linspace(0, 1, 10)

# Example usage
equal_spaced_array = generate_equal_spaced_array()

print("Equally spaced array:", equal_spaced_array)


Equally spaced array: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


# 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

In [14]:
import numpy as np

def generate_log_spaced_array():
    return np.logspace(0, 3, 5)  # log10(1) is 0 and log10(1000) is 3

# Example usage
log_spaced_array = generate_log_spaced_array()

print("Logarithmically spaced array:", log_spaced_array)


Logarithmically spaced array: [   1.            5.62341325   31.6227766   177.827941   1000.        ]


# 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100

In [15]:
import numpy as np
import pandas as pd

# Generate a NumPy array with random integers between 1 and 100
data = np.random.randint(1, 101, size=(5, 3))

# Create a Pandas DataFrame using the NumPy array
df = pd.DataFrame(data, columns=['Column1', 'Column2', 'Column3'])

# Print the DataFrame
print(df)


   Column1  Column2  Column3
0       54       37       14
1       27       16       64
2        1       51       25
3       47       32       82
4       46       66       71


# 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

In [16]:
import numpy as np
import pandas as pd

def replace_negatives_with_zeros(df, column_name):
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df

# Example usage
data = {'A': [1, -2, 3, -4, 5], 'B': [5, -6, 7, -8, 9]}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

# Replace negative values in column 'A' with zeros
df = replace_negatives_with_zeros(df, 'A')

print("\nDataFrame after replacing negatives in column 'A' with zeros:")
print(df)


Original DataFrame:
   A  B
0  1  5
1 -2 -6
2  3  7
3 -4 -8
4  5  9

DataFrame after replacing negatives in column 'A' with zeros:
   A  B
0  1  5
1  0 -6
2  3  7
3  0 -8
4  5  9


# 26. Access the 3rd element from the given NumPy array. arr = np.array([10, 20, 30, 40, 50])

In [17]:
import numpy as np

# Given array
arr = np.array([10, 20, 30, 40, 50])

# Access the 3rd element (index 2)
third_element = arr[2]

print("The 3rd element is:", third_element)


The 3rd element is: 30


# 27. Retrieve the element at index (1, 2) from the 2D NumPy array.
# arr_2d = np.array([[1, 2, 3],
 # [4, 5, 6],
 # [7, 8, 9]])

In [18]:
import numpy as np

# Given 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Access the element at index (1, 2)
element = arr_2d[1, 2]

print("The element at index (1, 2) is:", element)


The element at index (1, 2) is: 6


#  28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
 # arr = np.array([3, 8, 2, 10, 5, 7])

In [20]:
import numpy as np

# Given array
arr = np.array([3, 8, 2, 10, 5, 7])

# Extract elements greater than 5 using boolean indexing
elements_greater_than_5 = arr[arr > 5]

print("Elements greater than 5:", elements_greater_than_5)

Elements greater than 5: [ 8 10  7]


 # 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
 # arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
import numpy as np

# Given array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Extract elements from index 2 to 5 (inclusive)
sliced_elements = arr[2:6]

print("Elements from index 2 to 5 (inclusive):", sliced_elements)


Elements from index 2 to 5 (inclusive): [3 4 5 6]


# 30. Slice the 2D NumPy array to extract the sub-array [[2, 3], [5, 6]] from the given array.
 # arr_2d = np.array([[1, 2, 3],
 # [4, 5, 6],
 # [7, 8, 9]])

In [22]:
import numpy as np

# Given 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Extract the sub-array [[2, 3], [5, 6]]
sub_array = arr_2d[0:2, 1:3]

print("Sub-array [[2, 3], [5, 6]]:")
print(sub_array)


Sub-array [[2, 3], [5, 6]]:
[[2 3]
 [5 6]]


# 31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.

In [1]:
import numpy as np

def extract_elements_by_indices(arr_2d, indices):
    return arr_2d[indices[:, 0], indices[:, 1]]

# Example usage
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Indices to extract elements (each pair is a row and column index)
indices = np.array([[0, 1],  # Element at (0, 1)
                    [2, 0],  # Element at (2, 0)
                    [1, 2]]) # Element at (1, 2)

# Extract elements based on indices
extracted_elements = extract_elements_by_indices(arr_2d, indices)

print("Extracted elements:", extracted_elements)


Extracted elements: [2 7 6]


# 32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

In [2]:
import numpy as np

def filter_elements_greater_than_threshold(arr, threshold):
    return arr[arr > threshold]

# Example usage
arr = np.array([1, 5, 8, 3, 7, 2, 10])
threshold = 5

# Filter elements greater than the threshold
filtered_elements = filter_elements_greater_than_threshold(arr, threshold)

print("Original array:", arr)
print("Filtered elements greater than", threshold, ":", filtered_elements)


Original array: [ 1  5  8  3  7  2 10]
Filtered elements greater than 5 : [ 8  7 10]


# 33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.

In [3]:
import numpy as np

def extract_elements_3d(arr, idx1, idx2, idx3):
    return arr[idx1, idx2, idx3]

# Example usage
arr_3d = np.array([[[ 1,  2,  3],
                    [ 4,  5,  6],
                    [ 7,  8,  9]],
                   
                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]],
                   
                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]])

# Indices to extract elements
idx1 = np.array([0, 1, 2])  # Indices for the first dimension
idx2 = np.array([1, 2, 0])  # Indices for the second dimension
idx3 = np.array([2, 0, 1])  # Indices for the third dimension

# Extract elements based on indices
extracted_elements = extract_elements_3d(arr_3d, idx1, idx2, idx3)

print("Extracted elements:", extracted_elements)


Extracted elements: [ 6 16 20]


# 34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing

In [5]:
import numpy as np

def filter_elements_by_two_conditions(arr, condition1, condition2):
    return arr[np.logical_and(condition1, condition2)]

# Example usage
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Define two conditions
condition1 = arr > 3
condition2 = arr < 8

# Filter elements where both conditions are satisfied
filtered_elements = filter_elements_by_two_conditions(arr, condition1, condition2)

print("Original array:", arr)
print("Filtered elements (arr > 3 and arr < 8):", filtered_elements)


Original array: [ 1  2  3  4  5  6  7  8  9 10]
Filtered elements (arr > 3 and arr < 8): [4 5 6 7]


# 35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

In [6]:
import numpy as np

def extract_elements_by_row_col_indices(arr, row_indices, col_indices):
    return arr[row_indices, col_indices]

# Example usage
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Row and column indices to extract elements
row_indices = np.array([0, 1, 2])  # Row indices
col_indices = np.array([2, 1, 0])  # Column indices

# Extract elements based on row and column indices
extracted_elements = extract_elements_by_row_col_indices(arr_2d, row_indices, col_indices)

print("Original 2D array:")
print(arr_2d)
print("Extracted elements:", extracted_elements)


Original 2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Extracted elements: [3 5 7]


#  36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

In [7]:
import numpy as np

# Given array of shape (3, 3)
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Add a scalar value of 5 to each element
arr_plus_5 = arr + 5

print("Original array:")
print(arr)
print("\nArray after adding 5 to each element:")
print(arr_plus_5)


Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array after adding 5 to each element:
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


#  37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.

In [8]:
import numpy as np

# Define the given arrays
arr1 = np.array([[2, 3, 4]])  # Shape (1, 3)
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 10, 11, 12]])  # Shape (3, 4)

# Reshape arr1 to be (3, 1) so it can be broadcast across each row of arr2
arr1_reshaped = arr1.T  # Transpose arr1 to shape (3, 1)

# Multiply each row of arr2 by the corresponding element in arr1
result = arr2 * arr1_reshaped

print("Array arr1:")
print(arr1)
print("\nArray arr2:")
print(arr2)
print("\nResult after broadcasting and multiplying:")
print(result)


Array arr1:
[[2 3 4]]

Array arr2:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Result after broadcasting and multiplying:
[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


#  38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

In [9]:
import numpy as np

# Define the given arrays
arr1 = np.array([1, 2, 3, 4])  # Shape (4,)
arr2 = np.array([[ 5,  6,  7],
                 [ 8,  9, 10],
                 [11, 12, 13],
                 [14, 15, 16]])  # Shape (4, 3)

# Reshape arr1 to be compatible with arr2 for broadcasting
arr1_reshaped = arr1[:, np.newaxis]  # Shape (4, 1)

# Add arr1 to each row of arr2
result = arr2 + arr1_reshaped

print("Array arr1:")
print(arr1)
print("\nArray arr2:")
print(arr2)
print("\nResult after broadcasting and adding:")
print(result)


Array arr1:
[1 2 3 4]

Array arr2:
[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]
 [14 15 16]]

Result after broadcasting and adding:
[[ 6  7  8]
 [10 11 12]
 [14 15 16]
 [18 19 20]]


# 39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

In [10]:
import numpy as np

# Define the given arrays
arr1 = np.array([[1], 
                 [2], 
                 [3]])  # Shape (3, 1)
arr2 = np.array([[4, 5, 6]])  # Shape (1, 3)

# Add the arrays using broadcasting
result = arr1 + arr2

print("Array arr1:")
print(arr1)
print("\nArray arr2:")
print(arr2)
print("\nResult after broadcasting and adding:")
print(result)


Array arr1:
[[1]
 [2]
 [3]]

Array arr2:
[[4 5 6]]

Result after broadcasting and adding:
[[5 6 7]
 [6 7 8]
 [7 8 9]]


# 40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.

In [1]:
import numpy as np

# Define the given arrays
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])  # Shape (2, 3)
arr2 = np.array([[7, 8],
                 [9, 10]])  # Shape (2, 2)

# To handle the shape incompatibility, we need to extend arr2's shape to be compatible with arr1
# Repeat arr2 along the second axis to match arr1's shape
arr2_expanded = np.hstack((arr2, arr2[:, :1]))

# Perform the multiplication using broadcasting
result = arr1 * arr2_expanded

print("Array arr1:")
print(arr1)
print("\nArray arr2 (after expansion):")
print(arr2_expanded)
print("\nResult after broadcasting and multiplying:")
print(result)


Array arr1:
[[1 2 3]
 [4 5 6]]

Array arr2 (after expansion):
[[ 7  8  7]
 [ 9 10  9]]

Result after broadcasting and multiplying:
[[ 7 16 21]
 [36 50 54]]


# 41. Calculate column-wise mean for the given array: arr = np.array([[1, 2, 3], [4, 5, 6]])

In [3]:
import numpy as np

# Given array
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

# Calculate column-wise mean
column_wise_mean = np.mean(arr, axis=0)

print("Original array:")
print(arr)
print("\nColumn-wise mean:")
print(column_wise_mean)


Original array:
[[1 2 3]
 [4 5 6]]

Column-wise mean:
[2.5 3.5 4.5]


#   42. Find maximum value in each row of the given array:  arr = np.array([[1, 2, 3], [4, 5, 6]])

In [4]:
import numpy as np

# Given array
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

# Find maximum value in each row
row_wise_max = np.max(arr, axis=1)

print("Original array:")
print(arr)
print("\nMaximum value in each row:")
print(row_wise_max)


Original array:
[[1 2 3]
 [4 5 6]]

Maximum value in each row:
[3 6]


#  43. For the given array, find indices of maximum value in each column.    arr = np.array([[1, 2, 3], [4, 5, 6]])

In [5]:
import numpy as np

# Given array
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

# Find indices of maximum value in each column
column_wise_max_indices = np.argmax(arr, axis=0)

print("Original array:")
print(arr)
print("\nIndices of maximum value in each column:")
print(column_wise_max_indices)


Original array:
[[1 2 3]
 [4 5 6]]

Indices of maximum value in each column:
[1 1 1]


#  44. For the given array, apply custom function to calculate moving sum along rows.   arr = np.array([[1, 2, 3], [4, 5, 6]])

In [1]:
import numpy as np

def moving_sum(arr, window_size=2):
    # Create an empty array to store the results
    result = np.zeros_like(arr)
    
    # Calculate the moving sum for each row
    for i in range(arr.shape[0]):
        for j in range(arr.shape[1]):
            if j < window_size - 1:
                result[i, j] = np.sum(arr[i, :j+1])
            else:
                result[i, j] = np.sum(arr[i, j-window_size+1:j+1])
    
    return result

# Given array
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

# Apply the custom function to calculate the moving sum along rows
moving_sum_result = moving_sum(arr, window_size=2)

print("Original array:")
print(arr)
print("\nMoving sum along rows (window size 2):")
print(moving_sum_result)


Original array:
[[1 2 3]
 [4 5 6]]

Moving sum along rows (window size 2):
[[ 1  3  5]
 [ 4  9 11]]


# 45. In the given array, check if all elements in each column are even.             arr = np.array([[2, 4, 6], [3, 5, 7]])

In [3]:
import numpy as np

# Given array
arr = np.array([[2, 4, 6], 
                [3, 5, 7]])

# Check if all elements in each column are even
even_check = (arr % 2 == 0)
all_even_columns = np.all(even_check, axis=0)

print("Original array:")
print(arr)
print("\nCheck if all elements in each column are even:")
print(all_even_columns)

Original array:
[[2 4 6]
 [3 5 7]]

Check if all elements in each column are even:
[False False False]


# 46. Given a NumPy array arr, reshape it into a matrix of dimensions m rows and n columns. Return the reshaped matrix.    original_array = np.array([1, 2, 3, 4, 5, 6])

In [4]:
import numpy as np

def reshape_array(arr, m, n):
    return arr.reshape(m, n)

# Given array
original_array = np.array([1, 2, 3, 4, 5, 6])

# Specify the dimensions for reshaping
m = 2
n = 3

# Reshape the array
reshaped_matrix = reshape_array(original_array, m, n)

print("Original array:")
print(original_array)
print("\nReshaped matrix ({} rows, {} columns):".format(m, n))
print(reshaped_matrix)


Original array:
[1 2 3 4 5 6]

Reshaped matrix (2 rows, 3 columns):
[[1 2 3]
 [4 5 6]]


# 47. Create a function that takes a matrix as input and returns the flattened array.                                       input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

In [5]:
import numpy as np

def flatten_matrix(matrix):
    return matrix.flatten()

# Example input matrix
input_matrix = np.array([[1, 2, 3], 
                         [4, 5, 6]])

# Flatten the matrix
flattened_array = flatten_matrix(input_matrix)

print("Input matrix:")
print(input_matrix)
print("\nFlattened array:")
print(flattened_array)


Input matrix:
[[1 2 3]
 [4 5 6]]

Flattened array:
[1 2 3 4 5 6]


# 48. Write a function that concatenates two given arrays along a specified axis.         array1 = np.array([[1, 2], [3, 4]])           array2 = np.array([[5, 6], [7, 8]])

In [6]:
import numpy as np

def concatenate_arrays(arr1, arr2, axis):
    return np.concatenate((arr1, arr2), axis=axis)

# Example input arrays
array1 = np.array([[1, 2], 
                   [3, 4]])
array2 = np.array([[5, 6], 
                   [7, 8]])

# Concatenate arrays along axis 0 (rows)
concatenated_array_axis0 = concatenate_arrays(array1, array2, axis=0)
print("Concatenated array along axis 0 (rows):")
print(concatenated_array_axis0)

# Concatenate arrays along axis 1 (columns)
concatenated_array_axis1 = concatenate_arrays(array1, array2, axis=1)
print("\nConcatenated array along axis 1 (columns):")
print(concatenated_array_axis1)


Concatenated array along axis 0 (rows):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenated array along axis 1 (columns):
[[1 2 5 6]
 [3 4 7 8]]


#  49. Create a function that splits an array into multiple sub-arrays along a specified axis.     original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [7]:
import numpy as np

def split_array(arr, indices_or_sections, axis=0):
    return np.split(arr, indices_or_sections, axis=axis)

# Example input array
original_array = np.array([[1, 2, 3], 
                           [4, 5, 6], 
                           [7, 8, 9]])

# Specify the number of sections to split into or the indices
indices_or_sections = 3  # Split into 3 equal parts along the specified axis

# Split the array along axis 0 (rows)
split_arrays_axis0 = split_array(original_array, indices_or_sections, axis=0)
print("Original array:")
print(original_array)
print("\nSplit arrays along axis 0 (rows):")
for i, sub_array in enumerate(split_arrays_axis0):
    print(f"Sub-array {i}:")
    print(sub_array)

# Split the array along axis 1 (columns)
split_arrays_axis1 = split_array(original_array, indices_or_sections, axis=1)
print("\nSplit arrays along axis 1 (columns):")
for i, sub_array in enumerate(split_arrays_axis1):
    print(f"Sub-array {i}:")
    print(sub_array)


Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Split arrays along axis 0 (rows):
Sub-array 0:
[[1 2 3]]
Sub-array 1:
[[4 5 6]]
Sub-array 2:
[[7 8 9]]

Split arrays along axis 1 (columns):
Sub-array 0:
[[1]
 [4]
 [7]]
Sub-array 1:
[[2]
 [5]
 [8]]
Sub-array 2:
[[3]
 [6]
 [9]]


#  50. Write a function that inserts and then deletes elements from a given array at specified indices.  original_array = np.array([1, 2, 3, 4, 5])  indices_to_insert = [2, 4]   values_to_insert = [10, 11]    indices_to_delete = [1, 3]

In [8]:
import numpy as np

def insert_and_delete_elements(arr, indices_to_insert, values_to_insert, indices_to_delete):
    # Insert elements at specified indices
    arr_with_insertions = np.insert(arr, indices_to_insert, values_to_insert)
    
    # Adjust indices to delete after insertions
    adjusted_indices_to_delete = np.array(indices_to_delete) + np.searchsorted(indices_to_insert, indices_to_delete, side='right')
    
    # Delete elements at specified indices
    arr_with_deletions = np.delete(arr_with_insertions, adjusted_indices_to_delete)
    
    return arr_with_deletions

# Example input
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

# Insert and delete elements
result_array = insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)

print("Original array:")
print(original_array)
print("\nArray after insertions:")
print(np.insert(original_array, indices_to_insert, values_to_insert))
print("\nArray after deletions:")
print(result_array)


Original array:
[1 2 3 4 5]

Array after insertions:
[ 1  2 10  3  4 11  5]

Array after deletions:
[ 1 10  3 11  5]


#  51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.

In [1]:
import numpy as np

# Create arr1 with random integers (let's assume the same shape as arr2 for simplicity)
arr1 = np.random.randint(0, 100, size=10)

# Create arr2 with integers from 1 to 10
arr2 = np.arange(1, 11)

# Perform element-wise addition
result = arr1 + arr2

print("Array arr1 (random integers):")
print(arr1)
print("\nArray arr2 (integers from 1 to 10):")
print(arr2)
print("\nResult of element-wise addition:")
print(result)


Array arr1 (random integers):
[84 25 43 74  7 34 64 28 12 47]

Array arr2 (integers from 1 to 10):
[ 1  2  3  4  5  6  7  8  9 10]

Result of element-wise addition:
[85 27 46 78 12 40 71 36 21 57]


# 52. Generate a NumPy array arr1 with sequential integers from 10 to 1 and another array arr2 with integers from 1 to 10. Subtract arr2 from arr1 element-wise

In [2]:
import numpy as np

# Create arr1 with sequential integers from 10 to 1
arr1 = np.arange(10, 0, -1)

# Create arr2 with integers from 1 to 10
arr2 = np.arange(1, 11)

# Perform element-wise subtraction
result = arr1 - arr2

print("Array arr1 (sequential integers from 10 to 1):")
print(arr1)
print("\nArray arr2 (integers from 1 to 10):")
print(arr2)
print("\nResult of element-wise subtraction (arr1 - arr2):")
print(result)


Array arr1 (sequential integers from 10 to 1):
[10  9  8  7  6  5  4  3  2  1]

Array arr2 (integers from 1 to 10):
[ 1  2  3  4  5  6  7  8  9 10]

Result of element-wise subtraction (arr1 - arr2):
[ 9  7  5  3  1 -1 -3 -5 -7 -9]


#  53. Create a NumPy array arr1 with random integers and another array arr2 with integers from 1 to 5. Perform element-wise multiplication between arr1 and arr2.

In [3]:
import numpy as np

# Create arr1 with random integers (let's assume the same shape as arr2 for simplicity)
arr1 = np.random.randint(0, 100, size=5)

# Create arr2 with integers from 1 to 5
arr2 = np.arange(1, 6)

# Perform element-wise multiplication
result = arr1 * arr2

print("Array arr1 (random integers):")
print(arr1)
print("\nArray arr2 (integers from 1 to 5):")
print(arr2)
print("\nResult of element-wise multiplication:")
print(result)


Array arr1 (random integers):
[97 76  8 49 28]

Array arr2 (integers from 1 to 5):
[1 2 3 4 5]

Result of element-wise multiplication:
[ 97 152  24 196 140]


#  54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.

In [4]:
import numpy as np

# Create arr1 with even integers from 2 to 10
arr1 = np.arange(2, 11, 2)

# Create arr2 with integers from 1 to 5
arr2 = np.arange(1, 6)

# Perform element-wise division
result = arr1 / arr2

print("Array arr1 (even integers from 2 to 10):")
print(arr1)
print("\nArray arr2 (integers from 1 to 5):")
print(arr2)
print("\nResult of element-wise division (arr1 / arr2):")
print(result)

Array arr1 (even integers from 2 to 10):
[ 2  4  6  8 10]

Array arr2 (integers from 1 to 5):
[1 2 3 4 5]

Result of element-wise division (arr1 / arr2):
[2. 2. 2. 2. 2.]


# 55. Create a NumPy array arr1 with integers from 1 to 5 and another array arr2 with the same numbers reversed. Calculate the exponentiation of arr1 raised to the power of arr2 element-wise.

In [5]:
import numpy as np

# Create arr1 with integers from 1 to 5
arr1 = np.arange(1, 6)

# Create arr2 with the same numbers reversed
arr2 = arr1[::-1]

# Perform element-wise exponentiation
result = np.power(arr1, arr2)

print("Array arr1 (integers from 1 to 5):")
print(arr1)
print("\nArray arr2 (integers from 1 to 5, reversed):")
print(arr2)
print("\nResult of element-wise exponentiation (arr1 ** arr2):")
print(result)


Array arr1 (integers from 1 to 5):
[1 2 3 4 5]

Array arr2 (integers from 1 to 5, reversed):
[5 4 3 2 1]

Result of element-wise exponentiation (arr1 ** arr2):
[ 1 16 27 16  5]


#  56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.      arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

In [6]:
import numpy as np

def count_substring_occurrences(arr, substring):
    # Use vectorized string operations to count occurrences of the substring in each element
    count = np.char.count(arr, substring)
    # Sum the counts to get the total occurrences in the array
    total_occurrences = np.sum(count)
    return total_occurrences

# Example input array
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

# Specify the substring to count
substring = 'hello'

# Count occurrences of the substring
occurrences = count_substring_occurrences(arr, substring)

print(f"The substring '{substring}' occurs {occurrences} times in the array.")


The substring 'hello' occurs 3 times in the array.


#  57. Write a function that extracts uppercase characters from a NumPy array of strings.       arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])           arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

In [8]:
import numpy as np

def extract_uppercase_characters(arr):
    # Initialize an empty list to store the uppercase characters
    uppercase_characters = []
    
    # Iterate over each string in the array
    for string in arr:
        # Extract uppercase characters from the string
        uppercase_chars = ''.join([char for char in string if char.isupper()])
        uppercase_characters.append(uppercase_chars)
    
    # Convert the list of uppercase characters to a NumPy array
    result = np.array(uppercase_characters)
    return result

# Example input array
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

# Extract uppercase characters
uppercase_characters_array = extract_uppercase_characters(arr)

print("Original array:")
print(arr)
print("\nUppercase characters extracted:")
print(uppercase_characters_array)


Original array:
['Hello' 'World' 'OpenAI' 'GPT']

Uppercase characters extracted:
['H' 'W' 'OAI' 'GPT']


# 58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.         arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [9]:
import numpy as np

def replace_substring(arr, old_substring, new_substring):
    # Use np.char.replace to replace occurrences of old_substring with new_substring
    replaced_array = np.char.replace(arr, old_substring, new_substring)
    return replaced_array

# Example input array
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# Replace occurrences of 'apple' with 'orange'
old_substring = 'apple'
new_substring = 'orange'

# Replace substring
replaced_array = replace_substring(arr, old_substring, new_substring)

print("Original array:")
print(arr)
print("\nArray after replacing substring:")
print(replaced_array)


Original array:
['apple' 'banana' 'grape' 'pineapple']

Array after replacing substring:
['orange' 'banana' 'grape' 'pineorange']


#  59. Write a function that concatenates strings in a NumPy array element-wise.    arr1 = np.array(['Hello', 'World'])         arr2 = np.array(['Open', 'AI'])

In [10]:
import numpy as np

def concatenate_strings_elementwise(arr1, arr2):
    # Use np.char.add to concatenate the strings element-wise
    concatenated_array = np.char.add(arr1, arr2)
    return concatenated_array

# Example input arrays
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

# Concatenate strings element-wise
concatenated_array = concatenate_strings_elementwise(arr1, arr2)

print("Array arr1:")
print(arr1)
print("\nArray arr2:")
print(arr2)
print("\nConcatenated array:")
print(concatenated_array)


Array arr1:
['Hello' 'World']

Array arr2:
['Open' 'AI']

Concatenated array:
['HelloOpen' 'WorldAI']


#  60. Write a function that finds the length of the longest string in a NumPy array.     arr = np.array(['apple', 'banana', 'grape', 'pineapple'])     arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [11]:
import numpy as np

def find_longest_string_length(arr):
    # Use np.vectorize to apply the len function to each element in the array
    lengths = np.vectorize(len)(arr)
    # Find the maximum length
    max_length = np.max(lengths)
    return max_length

# Example input array
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# Find the length of the longest string
longest_string_length = find_longest_string_length(arr)

print("Array:")
print(arr)
print("\nLength of the longest string:")
print(longest_string_length)


Array:
['apple' 'banana' 'grape' 'pineapple']

Length of the longest string:
9


# 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.

In [12]:
import numpy as np

# Create a dataset of 100 random integers between 1 and 1000
dataset = np.random.randint(1, 1001, size=100)

# Compute the mean
mean_value = np.mean(dataset)

# Compute the median
median_value = np.median(dataset)

# Compute the variance
variance_value = np.var(dataset)

# Compute the standard deviation
std_deviation_value = np.std(dataset)

print("Dataset:")
print(dataset)
print("\nMean:", mean_value)
print("Median:", median_value)
print("Variance:", variance_value)
print("Standard Deviation:", std_deviation_value)


Dataset:
[688 149 329 676 534 482 421 470 344  10 974 872 829  65  83 649 805 599
 243 276 495 791 255 478  30 473 816 882 942 735 580 766 209  11 476 607
 118 871 410 326 121 649  65 418 904 872 468 259 150 632 582 631 160 761
 437 971 370 868 961 526 753 543 251 110  43 735 439 602 915 941 647 370
  42 339 871 152 740 154 463 430 886 344 358  48 837 585 308 768 231 391
 240  18 768 291 555 354 811  99 650 444]

Mean: 491.0
Median: 474.5
Variance: 78947.2
Standard Deviation: 280.97544376688865


#  62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

In [13]:
import numpy as np

# Generate an array of 50 random numbers between 1 and 100
dataset = np.random.randint(1, 101, size=50)

# Find the 25th percentile
percentile_25 = np.percentile(dataset, 25)

# Find the 75th percentile
percentile_75 = np.percentile(dataset, 75)

print("Dataset:")
print(dataset)
print("\n25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)

Dataset:
[27 27 69 90 88  6 51 39 90 60 67 96 49  5 45  5 89  5 44 50 44 62 85 46
 69 66 31 15 55 14 18 96 28 58 51  4  8 20 72 75 43 31  1 13 26 97 72 55
 13 67]

25th Percentile: 21.5
75th Percentile: 68.5


#  63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.

In [14]:
import numpy as np

# Create two arrays representing two sets of variables
array1 = np.random.randint(1, 100, size=50)
array2 = np.random.randint(1, 100, size=50)

# Compute the correlation coefficient matrix
correlation_matrix = np.corrcoef(array1, array2)

# Extract the correlation coefficient (off-diagonal element)
correlation_coefficient = correlation_matrix[0, 1]

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nCorrelation coefficient matrix:")
print(correlation_matrix)
print("\nCorrelation coefficient between Array 1 and Array 2:")
print(correlation_coefficient)


Array 1:
[78 73 27 99 24 99 43 46  3 66 15 11 16 47 11 60 73  9 55 12 30 27 23 79
  4 52 34 38 87 30 11  9 22 31 90 71 67 85 77 67 40 34  7 62  4  6 88  4
 83 61]

Array 2:
[ 8 22 17 45 47  6 53 39 32 27 17 93 95 23 28 85 67 97 18 46 32  9 89 40
 69 65 54 37  3 71 45 99 20 66 49 83 95 29 17 21 49 42 60  8 55 77 69 84
 75 54]

Correlation coefficient matrix:
[[ 1.         -0.30979126]
 [-0.30979126  1.        ]]

Correlation coefficient between Array 1 and Array 2:
-0.3097912621528588


#  64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.

In [15]:
import numpy as np

# Create two matrices
matrix1 = np.array([[1, 2, 3], 
                    [4, 5, 6]])
matrix2 = np.array([[7, 8], 
                    [9, 10], 
                    [11, 12]])

# Perform matrix multiplication
result = np.dot(matrix1, matrix2)

print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
print("\nResult of matrix multiplication (Matrix 1 dot Matrix 2):")
print(result)


Matrix 1:
[[1 2 3]
 [4 5 6]]

Matrix 2:
[[ 7  8]
 [ 9 10]
 [11 12]]

Result of matrix multiplication (Matrix 1 dot Matrix 2):
[[ 58  64]
 [139 154]]


#  65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

In [16]:
import numpy as np

# Create an array of 50 integers between 10 and 1000
arr = np.random.randint(10, 1001, size=50)

# Calculate the 10th percentile
percentile_10 = np.percentile(arr, 10)

# Calculate the 50th percentile (median)
percentile_50 = np.percentile(arr, 50)

# Calculate the 90th percentile
percentile_90 = np.percentile(arr, 90)

# Calculate the first quartile (25th percentile)
first_quartile = np.percentile(arr, 25)

# Calculate the third quartile (75th percentile)
third_quartile = np.percentile(arr, 75)

print("Array:")
print(arr)
print("\n10th Percentile:", percentile_10)
print("50th Percentile (Median):", percentile_50)
print("90th Percentile:", percentile_90)
print("First Quartile (25th Percentile):", first_quartile)
print("Third Quartile (75th Percentile):", third_quartile)


Array:
[759 693 105 145 837 696 318 111 486 710 407 189 598 940 101 748 322 472
 260 539 635 623 808 893 639 481 730 916 229 830 228 910 463 351 380 143
 759 389  85 743 212  34 268 642 525 463 550 947 493 284]

10th Percentile: 139.8
50th Percentile (Median): 489.5
90th Percentile: 842.6000000000001
First Quartile (25th Percentile): 272.0
Third Quartile (75th Percentile): 725.0


#  66. Create a NumPy array of integers and find the index of a specific element

In [17]:
import numpy as np

# Create a NumPy array of integers
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# Specify the element to find the index of
element_to_find = 50

# Find the index of the specific element
index_of_element = np.where(arr == element_to_find)[0]

print("Array:")
print(arr)
print(f"\nIndex of the element {element_to_find}:")
print(index_of_element)


Array:
[ 10  20  30  40  50  60  70  80  90 100]

Index of the element 50:
[4]


# 67. Generate a random NumPy array and sort it in ascending order

In [18]:
import numpy as np

# Generate a random NumPy array of 10 integers between 1 and 100
random_array = np.random.randint(1, 101, size=10)

# Sort the array in ascending order
sorted_array = np.sort(random_array)

print("Random array:")
print(random_array)
print("\nSorted array in ascending order:")
print(sorted_array)


Random array:
[18  6 44 15 27 12 27 24 43  8]

Sorted array in ascending order:
[ 6  8 12 15 18 24 27 27 43 44]


# 68. Filter elements >20  in the given NumPy array.    arr = np.array([12, 25, 6, 42, 8, 30])

In [19]:
import numpy as np

# Given array
arr = np.array([12, 25, 6, 42, 8, 30])

# Filter elements greater than 20
filtered_array = arr[arr > 20]

print("Original array:")
print(arr)
print("\nFiltered array (elements > 20):")
print(filtered_array)


Original array:
[12 25  6 42  8 30]

Filtered array (elements > 20):
[25 42 30]


# 69. Filter elements which are divisible by 3 from a given NumPy array.    arr = np.array([1, 5, 8, 12, 15])

In [20]:
import numpy as np

# Given array
arr = np.array([1, 5, 8, 12, 15])

# Filter elements divisible by 3
filtered_array = arr[arr % 3 == 0]

print("Original array:")
print(arr)
print("\nFiltered array (elements divisible by 3):")
print(filtered_array)


Original array:
[ 1  5  8 12 15]

Filtered array (elements divisible by 3):
[12 15]


# 70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.     arr = np.array([10, 20, 30, 40, 50])

In [21]:
import numpy as np

# Given array
arr = np.array([10, 20, 30, 40, 50])

# Filter elements which are ≥ 20 and ≤ 40
filtered_array = arr[(arr >= 20) & (arr <= 40)]

print("Original array:")
print(arr)
print("\nFiltered array (elements ≥ 20 and ≤ 40):")
print(filtered_array)


Original array:
[10 20 30 40 50]

Filtered array (elements ≥ 20 and ≤ 40):
[20 30 40]


#  71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.          arr = np.array([1, 2, 3])

In [22]:
import numpy as np

# Given array
arr = np.array([1, 2, 3])

# Check the byte order of the array
byte_order = arr.dtype.byteorder

print("Array:")
print(arr)
print("\nByte order of the array:")
print(byte_order)


Array:
[1 2 3]

Byte order of the array:
=


# 72. For the given NumPy array, perform byte swapping in place using byteswap().    arr = np.array([1, 2, 3], dtype=np.int32)

In [23]:
import numpy as np

# Given array
arr = np.array([1, 2, 3], dtype=np.int32)

print("Original array:")
print(arr)
print("Byte order of the original array:")
print(arr.dtype.byteorder)

# Perform byte swapping in place
arr.byteswap(True)

print("\nArray after byte swapping:")
print(arr)
print("Byte order of the array after swapping:")
print(arr.dtype.byteorder)


Original array:
[1 2 3]
Byte order of the original array:
=

Array after byte swapping:
[16777216 33554432 50331648]
Byte order of the array after swapping:
=


# 73. For the given NumPy array, swap its byte order without modifying the original array using newbyteorder().    arr = np.array([1, 2, 3], dtype=np.int32)

In [24]:
import numpy as np

# Given array
arr = np.array([1, 2, 3], dtype=np.int32)

print("Original array:")
print(arr)
print("Byte order of the original array:")
print(arr.dtype.byteorder)

# Swap the byte order without modifying the original array
swapped_arr = arr.byteswap().newbyteorder()

print("\nArray after byte swapping (without modifying the original array):")
print(swapped_arr)
print("Byte order of the swapped array:")
print(swapped_arr.dtype.byteorder)

# Verify the original array remains unchanged
print("\nOriginal array after attempting byte swap:")
print(arr)
print("Byte order of the original array:")
print(arr.dtype.byteorder)


Original array:
[1 2 3]
Byte order of the original array:
=

Array after byte swapping (without modifying the original array):
[1 2 3]
Byte order of the swapped array:
>

Original array after attempting byte swap:
[1 2 3]
Byte order of the original array:
=


# 74. For the given NumPy array and swap its byte order conditionally based on system endianness using newbyteorder().    arr = np.array([1, 2, 3], dtype=np.int32)

In [25]:
import numpy as np

# Given array
arr = np.array([1, 2, 3], dtype=np.int32)

print("Original array:")
print(arr)
print("Byte order of the original array:")
print(arr.dtype.byteorder)

# Determine the system's endianness
system_endianness = '<' if np.little_endian else '>'

# Swap byte order conditionally based on system endianness
if arr.dtype.byteorder == '=':
    # Native byte order, need to check system endianness
    if system_endianness == '<':
        swapped_arr = arr.byteswap().newbyteorder('>')
    else:
        swapped_arr = arr.byteswap().newbyteorder('<')
else:
    # Already in non-native byte order, simply swap back to native
    swapped_arr = arr.byteswap().newbyteorder('=')

print("\nArray after conditional byte swapping based on system endianness:")
print(swapped_arr)
print("Byte order of the swapped array:")
print(swapped_arr.dtype.byteorder)

# Verify the original array remains unchanged
print("\nOriginal array after attempting byte swap:")
print(arr)
print("Byte order of the original array:")
print(arr.dtype.byteorder)


Original array:
[1 2 3]
Byte order of the original array:
=

Array after conditional byte swapping based on system endianness:
[1 2 3]
Byte order of the swapped array:
>

Original array after attempting byte swap:
[1 2 3]
Byte order of the original array:
=


#  75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.    arr = np.array([1, 2, 3], dtype=np.int32)

In [1]:
import numpy as np

# Given array
arr = np.array([1, 2, 3], dtype=np.int32)

# Determine the system's endianness
system_endianness = '<' if np.little_endian else '>'

# Check if byte swapping is necessary
is_swap_needed = (arr.dtype.byteorder == '=') and (system_endianness != '=')

print("Original array:")
print(arr)
print("Byte order of the original array:")
print(arr.dtype.byteorder)
print("System endianness:")
print(system_endianness)
print("\nIs byte swapping necessary for the current system?")
print(is_swap_needed)

# Perform byte swap if necessary
if is_swap_needed:
    swapped_arr = arr.byteswap().newbyteorder()
    print("\nArray after byte swapping:")
    print(swapped_arr)
    print("Byte order of the swapped array:")
    print(swapped_arr.dtype.byteorder)
else:
    print("\nByte swapping is not necessary.")


Original array:
[1 2 3]
Byte order of the original array:
=
System endianness:
<

Is byte swapping necessary for the current system?
True

Array after byte swapping:
[1 2 3]
Byte order of the swapped array:
>


# 76. Create a NumPy array arr1 with values from 1 to 10. Create a copy of arr1 named copy_arr and modify an element in copy_arr. Check if modifying copy_arr affects arr1.

In [2]:
import numpy as np

# Create a NumPy array arr1 with values from 1 to 10
arr1 = np.arange(1, 11)

# Create a copy of arr1 named copy_arr
copy_arr = arr1.copy()

# Modify an element in copy_arr
copy_arr[0] = 99

# Check if modifying copy_arr affects arr1
print("Original array (arr1):")
print(arr1)

print("\nCopy of the array (copy_arr) after modification:")
print(copy_arr)

print("\nDoes modifying copy_arr affect arr1?")
print("No, arr1 remains unchanged.")


Original array (arr1):
[ 1  2  3  4  5  6  7  8  9 10]

Copy of the array (copy_arr) after modification:
[99  2  3  4  5  6  7  8  9 10]

Does modifying copy_arr affect arr1?
No, arr1 remains unchanged.


# 77. Create a 2D NumPy array matrix of shape (3, 3) with random integers. Extract a slice view_slice from the matrix. Modify an element in view_slice and observe if it changes the original matrix.

In [3]:
import numpy as np

# Create a 2D NumPy array matrix of shape (3, 3) with random integers
matrix = np.random.randint(1, 100, size=(3, 3))

# Extract a slice view_slice from the matrix
view_slice = matrix[:2, :2]

# Print the original matrix and the view_slice
print("Original matrix:")
print(matrix)

print("\nView slice of the matrix:")
print(view_slice)

# Modify an element in view_slice
view_slice[0, 0] = 999

# Print the modified view_slice and the original matrix to observe changes
print("\nModified view slice:")
print(view_slice)

print("\nMatrix after modifying the view slice:")
print(matrix)


Original matrix:
[[ 8  9 80]
 [85  3 29]
 [53 64 61]]

View slice of the matrix:
[[ 8  9]
 [85  3]]

Modified view slice:
[[999   9]
 [ 85   3]]

Matrix after modifying the view slice:
[[999   9  80]
 [ 85   3  29]
 [ 53  64  61]]


#  78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

In [4]:
import numpy as np

# Create a NumPy array array_a of shape (4, 3) with sequential integers from 1 to 12
array_a = np.arange(1, 13).reshape(4, 3)

# Extract a slice view_b from array_a
view_b = array_a[:2, :2]

# Print the original array and the view
print("Original array (array_a):")
print(array_a)

print("\nView slice (view_b) before modification:")
print(view_b)

# Broadcast the addition of 5 to view_b
view_b += 5

# Print the modified view and the original array to observe changes
print("\nView slice (view_b) after adding 5:")
print(view_b)

print("\nArray (array_a) after modifying the view slice:")
print(array_a)


Original array (array_a):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

View slice (view_b) before modification:
[[1 2]
 [4 5]]

View slice (view_b) after adding 5:
[[ 6  7]
 [ 9 10]]

Array (array_a) after modifying the view slice:
[[ 6  7  3]
 [ 9 10  6]
 [ 7  8  9]
 [10 11 12]]


# 79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.

In [5]:
import numpy as np

# Create a NumPy array orig_array of shape (2, 4) with values from 1 to 8
orig_array = np.arange(1, 9).reshape(2, 4)

# Create a reshaped view reshaped_view of shape (4, 2) from orig_array
reshaped_view = orig_array.reshape(4, 2)

# Print the original array and the reshaped view
print("Original array (orig_array):")
print(orig_array)

print("\nReshaped view (reshaped_view):")
print(reshaped_view)

# Modify an element in reshaped_view
reshaped_view[0, 0] = 99

# Print the modified reshaped view and the original array to observe changes
print("\nModified reshaped view (reshaped_view):")
print(reshaped_view)

print("\nOriginal array (orig_array) after modifying the reshaped view:")
print(orig_array)


Original array (orig_array):
[[1 2 3 4]
 [5 6 7 8]]

Reshaped view (reshaped_view):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Modified reshaped view (reshaped_view):
[[99  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]]

Original array (orig_array) after modifying the reshaped view:
[[99  2  3  4]
 [ 5  6  7  8]]


#  80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

In [6]:
import numpy as np

# Create a NumPy array data of shape (3, 4) with random integers
data = np.random.randint(1, 20, size=(3, 4))

# Extract a copy of elements greater than 5
data_copy = data[data > 5].copy()

# Print the original array and the copied array
print("Original array (data):")
print(data)

print("\nCopied array (data_copy) with elements greater than 5:")
print(data_copy)

# Modify an element in data_copy
if data_copy.size > 0:  # Ensure there is at least one element in the copy
    data_copy[0] = 99

# Print the modified copied array and the original array to observe changes
print("\nModified copied array (data_copy):")
print(data_copy)

print("\nOriginal array (data) after modifying the copied array:")
print(data)


Original array (data):
[[18 10  4  9]
 [ 1  7 13 16]
 [ 7  9 10  3]]

Copied array (data_copy) with elements greater than 5:
[18 10  9  7 13 16  7  9 10]

Modified copied array (data_copy):
[99 10  9  7 13 16  7  9 10]

Original array (data) after modifying the copied array:
[[18 10  4  9]
 [ 1  7 13 16]
 [ 7  9 10  3]]


# 81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

In [9]:
import numpy as np

# Create two matrices A and B of identical shape containing integers
A = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

B = np.array([[9, 8, 7], 
              [6, 5, 4], 
              [3, 2, 1]])

# Perform addition of matrices A and B
addition_result = A + B

# Perform subtraction of matrices A and B
subtraction_result = A - B

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nAddition of A and B:")
print(addition_result)

print("\nSubtraction of A and B:")
print(subtraction_result)


Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Addition of A and B:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Subtraction of A and B:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


# 82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

In [10]:
import numpy as np

# Generate two matrices C (3x2) and D (2x4) with random integers
C = np.random.randint(1, 10, size=(3, 2))
D = np.random.randint(1, 10, size=(2, 4))

# Perform matrix multiplication
multiplication_result = np.dot(C, D)

print("Matrix C (3x2):")
print(C)

print("\nMatrix D (2x4):")
print(D)

print("\nMatrix multiplication of C and D:")
print(multiplication_result)


Matrix C (3x2):
[[9 1]
 [4 1]
 [3 3]]

Matrix D (2x4):
[[3 8 1 6]
 [5 4 1 5]]

Matrix multiplication of C and D:
[[32 76 10 59]
 [17 36  5 29]
 [24 36  6 33]]


#  83. Create a matrix `E` and find its transpose.

In [11]:
import numpy as np

# Create a matrix E with random integers
E = np.random.randint(1, 10, size=(3, 4))

# Find the transpose of matrix E
E_transpose = E.T

print("Matrix E:")
print(E)

print("\nTranspose of matrix E:")
print(E_transpose)


Matrix E:
[[5 3 8 5]
 [3 4 8 2]
 [6 5 6 1]]

Transpose of matrix E:
[[5 3 6]
 [3 4 5]
 [8 8 6]
 [5 2 1]]


# 84. Generate a square matrix `F` and compute its determinant.

In [12]:
import numpy as np

# Generate a square matrix F (e.g., 3x3) with random integers
F = np.random.randint(1, 10, size=(3, 3))

# Compute the determinant of matrix F
determinant_F = np.linalg.det(F)

print("Square matrix F:")
print(F)

print("\nDeterminant of matrix F:")
print(determinant_F)


Square matrix F:
[[5 9 3]
 [3 8 9]
 [5 2 2]]

Determinant of matrix F:
238.9999999999999


#  85. Create a square matrix `G` and find its inverse.

In [13]:
import numpy as np

# Generate a square matrix G (e.g., 3x3) with random integers
G = np.random.randint(1, 10, size=(3, 3))

# Find the inverse of matrix G
try:
    inverse_G = np.linalg.inv(G)
    print("Square matrix G:")
    print(G)
    
    print("\nInverse of matrix G:")
    print(inverse_G)
except np.linalg.LinAlgError:
    print("Matrix G is singular and does not have an inverse.")


Square matrix G:
[[8 9 9]
 [4 7 1]
 [3 5 6]]

Inverse of matrix G:
[[ 0.37755102 -0.09183673 -0.55102041]
 [-0.21428571  0.21428571  0.28571429]
 [-0.01020408 -0.13265306  0.20408163]]
